sample/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add', views.add_sample, name='add_sample'),
    url(r'^test/all', views.TestsView.as_view(), name='all_tests'),
    url(r'^start/', views.start, name='start'),
    url(r'^exception/', views.ExceptionsView.as_view(), name='exception'),
    url(r'^(?P<test_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^elements/', views.elements, name='elements'),
    url(r'^forms/', views.forms, name='forms'),
    url(r'^pool/', views.pool, name='pool'),

]

testingJson/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('sample.urls', namespace="sample")),
    url(r'^admin/', admin.site.urls),
]

sample/models.py
from django.db import models

# Create your models here.



class TestObj(models.Model):
	def get_pairs_count(self):
		count = self.pair_set.count()
		return count


		


class Pair(models.Model):
	int_A = models.IntegerField(default=0)
	int_B = models.IntegerField(default=0)
	test = models.ForeignKey(TestObj, on_delete=models.CASCADE)


class Result(models.Model):
	test = models.ForeignKey(TestObj, on_delete=models.CASCADE)
	traceback = models.TextField(null=True)
	result = models.TextField(null=True)
	date = models.DateTimeField(auto_now=True)
	round = models.IntegerField(default=0)


def get_round():
	res = Result.objects.values_list('round').order_by('-id')[0][0]
	return res

sample/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, render,get_object_or_404
from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views import generic
from celery import chain
import json
import urllib3

from .tasks import getting,func,result
from .models import TestObj, Pair, Result, get_round

def index(request):
	latest_tests_list = TestObj.objects.order_by('-id')[:10]

	res = Result.objects.filter(round=get_round())
	res = res.exclude(result=None)

	if len(res)==0: ex = 1
	else: ex =0
	context = {'latest_tests_list': latest_tests_list,'ex':ex
			}
	return render(request, 'sample/index.html', context)




def add_sample(request, *args, **kwargs):
	d = '['+request.POST['sample_text']+']'
	pairs = json.loads(d)
	test = TestObj.objects.create()
	test.save()
	for pair in pairs:
		a = Pair.objects.create(int_A=pair['a'], int_B=pair['b'], test=test)
		a.save()

	return HttpResponseRedirect(reverse('sample:index'))


class TestsView(generic.ListView):
    template_name = 'sample/all_tests.html'
    context_object_name = 'tests_list'

    def get_queryset(self):
        return TestObj.objects.all()


def start(request, *args, **kwargs):
	tests = TestObj.objects.values_list('id')
	round = get_round()

	for test in tests:
		chain(getting.s(test[0]), func.s(), result.s([test[0],round]))()

	return HttpResponseRedirect(reverse('sample:index'))

def detail(request, test_id):
    test = TestObj.objects.get(id=test_id)
    result = Result.objects.filter(round=get_round(),test_id=test_id)[0]

    return render(request, 'sample/detail.html', {'test': test,'result':result})

class ExceptionsView(generic.ListView):
    template_name = 'sample/all_tests.html'
    context_object_name = 'tests_list'

    def get_queryset(self):
        return TestObj.objects.filter(result__result=None,result__round=get_round())

def elements(request, *args, **kwargs):
    return render(request, 'sample/bootstrap-elements.html')

def forms(request, *args, **kwargs):
	return render(request, 'sample/forms.html')


def pool(request, *args, **kwargs):
	http = urllib3.PoolManager()
	act=request.POST['act']
	size=request.POST['size']
	worker=request.POST['worker']

	r = http.request('POST', 'localhost:5555/api/worker/pool/'+act+'/celery@'+worker+'?n='+size)
	return HttpResponseRedirect(reverse('sample:index'))

sample/templates/sample/all_tests.html
{% extends 'sample/base.html' %}

{% block title %}Все тесты{% endblock %}
{% block content %}
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-6">
                        <h1 class="page-header">
                            Обзор <small>Overview</small>
                        </h1>
                    </div>  
                </div>
                
                <!-- /.row -->

            <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i> Все наборы</h3>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th>Набор #</th>
                                                <th>Количество пар</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for test in tests_list %}
                                            <tr>
                                                <td>{{test.id}}</td>
                                                <td>{{test.get_pairs_count}}</td>
                                                <td> <a href="{% url 'sample:detail' test.id %}"><button type="button" class="btn btn-primary">Детали</button></a></td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                      
                </div>
                <!-- /.row -->
                {% endblock %}

sample/templates/sample/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'sample/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'sample/css/sb-admin.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static 'sample/css/plugins/morris.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'sample/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">Testing serv.</a>
            </div>
            <!-- Top Menu Items -->

            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li class="active">
                        <a href="{% url 'sample:index' %}">Главная</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'sample:all_tests' %}">Все наборы</a>
                    </li>
                    <li class="active">
                        <a href="{% url 'sample:exception' %}">Эксепшены</a>
                    </li>
                    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">
            {% block content %}
            {% endblock %}


            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="{% static 'sample/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'sample/js/bootstrap.min.js' %}"></script>

    <!-- Morris Charts JavaScript -->
    <script src="{% static 'sample/js/plugins/morris/raphael.min.js' %}"></script>
    <script src="{% static 'sample/js/plugins/morris/morris.min.js' %}"></script>
    <script src="{% static 'sample/js/plugins/morris/morris-data.js' %}"></script>

</body>

</html>

sample/templates/sample/detail.html
{% extends 'sample/base.html' %}

{% block title %}Детали{% endblock %}
{% block content %}
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-6">
                        <h1 class="page-header">
                            Обзор <small>Overview</small>
                        </h1>
                    </div>  
                </div>
                
                <!-- /.row -->

            <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i> Все наборы</h3>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th>Набор #</th>
                                                <th>Количество пар</th>
                                                <th>Пары</th>
                                                <th>Последняя проверка</th>
                                                <th>Результат</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        
                                            <tr>
                                                <td>{{test.id}}</td>
                                                <td>{{test.get_pairs_count}}</td>
                                                <td>
                                                    {% for pair in test.pair_set.all %}
                                                         <li>a:{{ pair.int_A }}  b:{{ pair.int_B }}</li>
                                                    {% endfor %}
                                                </td>
                                                <td>{{result.date}}</td>
                                                <td>{{result.result}}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>
                    </div>
                      
                </div>
                {% if result.traceback %}
                <div class="row">
                    <div class="col-sm-8">
                        <div class="panel panel-red">
                            <div class="panel-heading">
                                <h3 class="panel-title">traceback</h3>
                            </div>
                            <div class="panel-body">
                                {{result.traceback}}
                            </div>
                        </div>
                    </div>

                </div>
                {% endif %}
                <!-- /.row -->
                {% endblock %}

sample/templates/sample/index.html
{% extends 'sample/base.html' %}

{% block title %}Главная{% endblock %}
{% block content %}
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-4">
                        <h1 class="page-header">
                            Обзор <small>Overview</small>
                        </h1>
                    </div>
                    <div class="col-lg-2">
                    <div class="text-left page-header">
                        <a href="{% url 'sample:start' %}"><button type="button" class="btn btn-lg btn-primary">Начать проверку</button></a>
                    </div> 
                    </div>
                    <div class="col-lg-6">
                        {% if ex %}
                            <div class="page-header alert alert-danger">
                                Во время прошлого тестирования были эксепшены!
                            </div>
                        {% else %}
                            <div class="page-header alert alert-success">
                                Последний тест прошел спокойно.
                            </div>
                        {% endif %}
                    </div>  
                    
                </div>

                
                <!-- /.row -->

            <div class="row">
                <div class="col-lg-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i> Добавление данных</h3>
                            </div>
                            <div class="panel-body">
                             <form role="form" action="{% url 'sample:add_sample' %}" method="POST">{% csrf_token %}

                            <div class="form-group">
                                <label>Набор</label>
                                <input class="form-control" name="sample_text" >
                                <p class="help-block">Введите в формате:{"a":1,"b":2},{"a":4,"b":-2},...</p>
                            </div>


                            <button type="submit" class="btn btn-default">Submit Button</button>
                            <button type="reset" class="btn btn-default">Reset Button</button>

                        </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-clock-o fa-fw"></i>Worker Control</h3>
                            </div>
                            <div class="panel-body">
                            <form role="form" action="{% url 'sample:pool' %}" method="POST">
                            {% csrf_token %}
                                <div class="form-group">

                                    <label>Pool Size Grow</label>
                                    <select class="form-control" name="size">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                    <select class="form-control" name="act">
                                        <option>grow</option>
                                        <option>shrink</option>
                                    </select>
                                    <select class="form-control" name="worker">
                                        <option>worker1</option>
                                        <option>worker2</option>
                                        <option>worker3</option>
                                    </select>
                                    <button type="submit" class="btn btn-default">Submit Button</button>

                                </div>
                                </form>
                            </div>
                        </div>
                    </div>

                      
                </div>
                <!-- /.row -->

        
            {% endblock %}